# Generated by Django 3.0.3 on 2020-03-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satuhati', '0002_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_id', models.CharField(max_length=11)),
                ('member_id', models.CharField(max_length=11)),
                ('liked_time', models.CharField(max_length=50)),
            ],
        ),
    ]
